---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

### Pavan Pyla

### 22232 MDSC - 202 (P)

## Defining the Matrix and Accesing elements

```{r}
A<- matrix(data=c(-1,-2,-3,-4,-5,-6,-7,-8),nrow=4,ncol=2,byrow=TRUE)

print(A)
```

```{r}
rbind(-1:8,1:10)       # Printing two rows withing given range
```

```{r}
cbind(c(1:9),c(2:10),c(3:11))       # Printing three columns
```

```{r}
print(A)
```

```{r}
nrow(A)      # printing the no of rows in matrix A
```

```{r}
ncol(A)     # printing the no of columns in matrix A

```

```{r}
dim(A)[1]       #Printg the dimension of column 1           
```

```{r}
print(A[4,2])             # Printg the elements in 
print(A[2,])
print(A[,2])
```

```{r}
print(A[2:4])     # Printing the elemsts of 2,3,4 in column 1
```

```{r}
print(A)
```

```{r}

```

```{r}
print(A[,-1])            #printing the matrix excluding column 1
```

```{r}
print(A)   #printing the matric
```

## Matrix Manupulations

```{r}
print(A[-1,-1]) #printing the matrix excluding row 1 and column 1

```

```{r}
b<-A
print(b)         #making a copy of the matrix
```

```{r}
b[2,]<-c(1,0)         #copying vector (1,0) in row 2  

print(b)
```

```{r}
b[c(2,3),2:1]<-c(99,0,1,2)     #manupulating matrix accordingly
print(b)
```

```{r}
print(b) 

```

```{r}
diag(x=b)<-rep(x=0,times=2)          #making diagonal elemnets 0 and multiplying 
                                     # Twice
print(b)
```
